In [7]:
import pandas as pd

# Load the CSV (replace with your actual filename if different)
df = pd.read_csv('/content/yellow_tripdata_2016-01.csv')  # e.g., 'yellow_tripdata_2023-01.csv'

# Display basic structure and sample rows
print("🔹 First 5 Rows:")
display(df.head())

print("\n🔹 Column Names:")
print(df.columns.tolist())

print("\n🔹 DataFrame Info:")
df.info()

print("\n🔹 Missing Values per Column:")
print(df.isnull().sum())

print("\n🔹 Summary Statistics (Numerical Columns):")
display(df.describe())

print("\n🔹 Unique Values, Min & Max per Column:")
for col in df.columns:
    try:
        print(f"\nColumn: {col}")
        print(f"  Type: {df[col].dtype}")
        print(f"  Unique values: {df[col].nunique()}")
        print(f"  Min: {df[col].min()}")
        print(f"  Max: {df[col].max()}")
    except:
        print(f"  Skipping column {col} due to incompatible type")

🔹 First 5 Rows:

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2016-01-01 00:00:00,2016-01-01 00:00:00,2,1.10,-73.990372,40.734695,1.0,N,-73.981842,40.732407,2.0,7.5,0.5,0.5,0.0,0.0,0.3,8.8
1,2,2016-01-01 00:00:00,2016-01-01 00:00:00,5,4.90,-73.980782,40.729912,1.0,N,-73.944473,40.716679,1.0,18.0,0.5,0.5,0.0,0.0,0.3,19.3
2,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,10.54,-73.984550,40.679565,1.0,N,-73.950272,40.788925,1.0,33.0,0.5,0.5,0.0,0.0,0.3,34.3
3,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,4.75,-73.993469,40.718990,1.0,N,-73.962242,40.657333,2.0,16.5,0.0,0.5,0.0,0.0,0.3,17.3
4,2,2016-01-01 00:00:00,2016-01-01 00:00:00,3,1.76,-73.960625,40.781330,1.0,N,-73.977264,40.758514,2.0,8.0,0.0,0.5,0.0,0.0,0.3,8.8

🔹 Column Names:
['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'pickup_longitude', 'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag', 'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount']

🔹 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5057808 entries, 0 to 5057807
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        int64
 4   trip_distance          float64
 5   pickup_longitude       float64
 6   pickup_latitude        float64
 7   RatecodeID             float64
 8   store_and_fwd_flag     object
 9   dropoff_longitude      float64
 10  dropoff_latitude       float64
 11  payment_type           float64
 12  fare_amount            float64
 13  extra                  float64
 14  mta_tax                float64
 15  tip_amount             float64
 16  tolls_amount           float64
 17  improvement_surcharge  float64
 18  total_amount           float64
dtypes: float64(14), int64(2), object(3)
memory usage: 733.2+ MB

🔹 Missing Values per Column:
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
pickup_longitude         0
pickup_latitude          0
RatecodeID               1
store_and_fwd_flag       1
dropoff_longitude        1
dropoff_latitude         1
payment_type             1
fare_amount              1
extra                    1
mta_tax                  1
tip_amount               1
tolls_amount             1
improvement_surcharge    1
total_amount             1
dtype: int64

🔹 Summary Statistics (Numerical Columns):

,VendorID,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,5.057808e+06,5.057808e+06,5.057808e+06,5.057808e+06,5.057808e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06,5.057807e+06
mean,1.411842e+00,1.580340e+00,6.209885e+00,-7.271758e+01,4.005932e+01,1.040809e+00,-7.279568e+01,4.010311e+01,1.361059e+00,1.257122e+01,3.027693e-01,4.975764e-01,1.729867e+00,2.970548e-01,2.997850e-01,1.569827e+01
std,4.921669e-01,1.213925e+00,4.240947e+03,9.554290e+00,5.263354e+00,5.864193e-01,9.258583e+00,5.100591e+00,4.983483e-01,1.153817e+01,4.620061e-01,4.136854e-02,2.672687e+00,1.817945e+00,1.085545e-02,1.398708e+01
min,1.000000e+00,0.000000e+00,0.000000e+00,-1.008229e+02,0.000000e+00,1.000000e+00,-1.008229e+02,0.000000e+00,1.000000e+00,-9.576000e+02,-3.564000e+01,-5.000000e-01,-7.000000e+01,-1.740000e+01,-3.000000e-01,-9.584000e+02
25%,1.000000e+00,1.000000e+00,1.000000e+00,-7.399146e+01,4.073598e+01,1.000000e+00,-7.399101e+01,4.073462e+01,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00
50%,1.000000e+00,1.000000e+00,1.690000e+00,-7.398128e+01,4.075353e+01,1.000000e+00,-7.397929e+01,4.075396e+01,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.250000e+00,0.000000e+00,3.000000e-01,1.162000e+01
75%,2.000000e+00,2.000000e+00,3.100000e+00,-7.396579e+01,4.076810e+01,1.000000e+00,-7.396175e+01,4.076948e+01,2.000000e+00,1.400000e+01,5.000000e-01,5.000000e-01,2.260000e+00,0.000000e+00,3.000000e-01,1.725000e+01
max,2.000000e+00,9.000000e+00,8.000010e+06,0.000000e+00,5.726928e+01,9.900000e+01,0.000000e+00,5.274897e+01,4.000000e+00,5.000000e+03,6.488700e+02,3.644000e+01,9.981400e+02,9.235800e+02,3.000000e-01,5.000800e+03

🔹 Unique Values, Min & Max per Column:

Column: VendorID
  Type: int64
  Unique values: 2
  Min: 1
  Max: 2

Column: tpep_pickup_datetime
  Type: object
  Unique values: 1332461
  Min: 2016-01-01 00:00:00
  Max: 2016-01-29 12:26:57

Column: tpep_dropoff_datetime
  Type: object
  Unique values: 1345237
  Min: 2016-01-01 00:00:00
  Max: 2016-01-31 01:01:07

Column: passenger_count
  Type: int64
  Unique values: 10
  Min: 0
  Max: 9

Column: trip_distance
  Type: float64
  Unique values: 3878
  Min: 0.0
  Max: 8000010.0

Column: pickup_longitude
  Type: float64
  Unique values: 30301
  Min: -100.82293701171876
  Max: 0.0

Column: pickup_latitude
  Type: float64
  Unique values: 56009
  Min: 0.0
  Max: 57.2692756652832

Column: RatecodeID
  Type: float64
  Unique values: 7
  Min: 1.0
  Max: 99.0

Column: store_and_fwd_flag
  Type: object
  Unique values: 2
  Skipping column store_and_fwd_flag due to incompatible type

Column: dropoff_longitude
  Type: float64
  Unique values: 45367
  Min: -100.82293701171876
  Max: 0.0

Column: dropoff_latitude
  Type: float64
  Unique values: 78558
  Min: 0.0
  Max: 52.748966217041016

Column: payment_type
  Type: float64
  Unique values: 4
  Min: 1.0
  Max: 4.0

Column: fare_amount
  Type: float64
  Unique values: 1299
  Min: -957.6
  Max: 5000.0

Column: extra
  Type: float64
  Unique values: 25
  Min: -35.64
  Max: 648.87

Column: mta_tax
  Type: float64
  Unique values: 10
  Min: -0.5
  Max: 36.44

Column: tip_amount
  Type: float64
  Unique values: 2807
  Min: -70.0
  Max: 998.14

Column: tolls_amount
  Type: float64
  Unique values: 689
  Min: -17.4
  Max: 923.58

Column: improvement_surcharge
  Type: float64
  Unique values: 3
  Min: -0.3
  Max: 0.3

Column: total_amount
  Type: float64
  Unique values: 8805
  Min: -958.4
  Max: 5000.8

In [12]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 1. Load CSV
df = pd.read_csv('/content/yellow_tripdata_2016-01.csv', parse_dates=[
    'tpep_pickup_datetime','tpep_dropoff_datetime'
])

# 2. Clean data (as discussed)
df = df.loc[
    (df.trip_distance.between(0.01, 100)) &
    (df.fare_amount >= 0) &
    (df.total_amount >= 0) &
    (df.passenger_count.between(1,6)) &
    (df.pickup_longitude.between(-75, -72)) &
    (df.pickup_latitude.between(40, 42)) &
    (df.dropoff_longitude.between(-75, -72)) &
    (df.dropoff_latitude.between(40, 42))
].copy()

# Q1. Add “Revenue”
df['Revenue'] = (
    df.fare_amount + df.extra + df.mta_tax +
    df.improvement_surcharge + df.tip_amount +
    df.tolls_amount + df.total_amount
)

# Q2. Increasing count of total passengers by “area”
#    bucket lat/lon to 2 decimal places
df['p_lat_b'] = df.pickup_latitude.round(2)
df['p_lon_b'] = df.pickup_longitude.round(2)
q2 = (
    df.groupby(['p_lat_b','p_lon_b'])
      .passenger_count.sum()
      .reset_index(name='total_passengers')
      .sort_values('total_passengers', ascending=True)
)
print("Q2: Passengers by area (asc):")
print(q2.head(10))

# Q3. Real‑time average fare & average Revenue by Vendor
q3 = (
    df.groupby('VendorID')
      .agg(avg_fare=('fare_amount','mean'),
           avg_revenue=('Revenue','mean'))
      .reset_index()
)
print("\nQ3: Avg fare & avg revenue per Vendor:")
print(q3)

# Q4. Moving count of payments by each payment mode
df = df.sort_values('tpep_pickup_datetime')
df['payment_mode_running_count'] = (
    df.groupby('payment_type')
      .cumcount() + 1
)
print("\nQ4: Sample running counts (payment_type):")
print(df[['payment_type','tpep_pickup_datetime','payment_mode_running_count']].head(10))

# Q5. Highest two gaining vendors on a date with total passengers & distance
date_to_analyze = pd.to_datetime('2016-01-15')
mask = df['tpep_pickup_datetime'].dt.date == date_to_analyze.date()
q5 = (
    df.loc[mask]
      .groupby('VendorID')
      .agg(total_revenue=('Revenue','sum'),
           total_passengers=('passenger_count','sum'),
           total_distance=('trip_distance','sum'))
      .reset_index()
      .sort_values('total_revenue', ascending=False)
      .head(2)
)
print(f"\nQ5: Top 2 vendors on {date_to_analyze.date()}:")
print(q5)

# Q6. Route with the most total passengers
q6 = (
    df.groupby([
        'pickup_longitude','pickup_latitude',
        'dropoff_longitude','dropoff_latitude'
    ])['passenger_count']
      .sum()
      .reset_index(name='passenger_sum')
      .sort_values('passenger_sum', ascending=False)
      .head(1)
)
print("\nQ6: Busiest route by passenger count:")
print(q6)

# Q7. Top pickup locations with most passengers in last N seconds
N = 10  # seconds
cutoff = datetime.utcnow() - timedelta(seconds=N)
# If your tpep times are in UTC—or convert accordingly—else use pd.Timestamp.now()
recent = df.loc[df.tpep_pickup_datetime >= cutoff]
q7 = (
    recent.groupby(['pickup_longitude','pickup_latitude'])
          .passenger_count.sum()
          .reset_index(name='passenger_sum')
          .sort_values('passenger_sum', ascending=False)
          .head(5)
)
print(f"\nQ7: Top pickup spots in last {N} seconds:")
print(q7)

Q2: Passengers by area (asc):
      p_lat_b  p_lon_b  total_passengers
1648    41.32   -74.12                 1
1645    41.31   -74.12                 1
1644    41.30   -72.93                 1
1630    41.16   -73.85                 1
1628    41.15   -73.78                 1
41      40.44   -74.15                 1
36      40.43   -74.18                 1
1639    41.24   -74.02                 1
1638    41.22   -73.20                 1
1637    41.21   -73.25                 1

Q3: Avg fare & avg revenue per Vendor:
   VendorID   avg_fare  avg_revenue
0         1  12.306146    30.851145
1         2  12.551414    31.452445

Q4: Sample running counts (payment_type):
   payment_type tpep_pickup_datetime  payment_mode_running_count
0             2  2016-01-01 00:00:00                           1
1             1  2016-01-01 00:00:00                           1
2             1  2016-01-01 00:00:00                           2
3             2  2016-01-01 00:00:00                           2
4             2  2016-01-01 00:00:00                           3
5             2  2016-01-01 00:00:00                           4
6             2  2016-01-01 00:00:00                           5
7             2  2016-01-01 00:00:01                           6
8             2  2016-01-01 00:00:02                           7
9             2  2016-01-01 00:00:02                           8

Q5: Top 2 vendors on 2016-01-15:
   VendorID  total_revenue  total_passengers  total_distance
1         2      6774817.8            425877       633067.67
0         1      5826239.5            226327       534175.50

Q6: Busiest route by passenger count:
         pickup_longitude  pickup_latitude  dropoff_longitude  \
9316657        -73.954666        40.821003         -73.954666

         dropoff_latitude  passenger_sum
9316657         40.821003           1500

Q7: Top pickup spots in last 10 seconds:
Empty DataFrame
Columns: [pickup_longitude, pickup_latitude, passenger_sum]
Index: []